import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
// import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Bento App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-nunito">
        <div className="">
          <Navbar />
        </div>
        <main className="">{children}</main>
        <div className="">
          <Footer />
        </div>
      </body>
    </html>
  );
}
